*Comments from latest Wkumler review*
Why not change options?

CL1
- I was thinking I'd prioritize good feedback ("columns are correct", "classes are correct", etc.) so it's clear that the functions are running. Some of them take more time than others.
- The rowwise is slow, but the entire run time of the function is still only <10 seconds. I could try an sapply solution to see if that speeds things up. What do you mean by NA handling inside the function?
- Make a better stop() function for compound check
- Handle NAs inside the ms2 cosine similarity function instead of the ifelse statements.

CL2

- Let's discuss adduct formation. The code that I have there (MH_mass +/-) is from KRH's original code and probably could use an update.
- When things weren't parallelized, it was taking a lot longer (maybe 5 mins?). I adjusted the code to run a check for OS and then parallel/nonparallel depending on output.

CL3
- Same code to prepare the Mona sheets, left as was for a) trying to have the steps be potentially independent and b) to retain access to the Mona metadata.
- Make a better stop() function for compound check

utils
- no hard coding if possible

*Notes*

- Styler package. style_pkg(), style_dir(), etc. Keep it tidy. Commit before application of style changes. See Ch 7.3 for deets.

- Check collision energy stuff.
- How to best update the "Theoretical Data" for CL1? Similar to the quarterly update/up-to-user update? 


Finalize KEGG creation code.

Finalize MoNA creation code.

Finalize Metlin query code and include it in the phobos package. It should be a non-parallelized small compound number search, aka hard to reach!

Incorporate existing KRH code to easily update the standards MS2 data.

Create functions to deal with the big, repetitive output csvs. Wrappers in the package should be able to handle various standard queries from the big database: Do we see this unknown feature anywhere in our data? Where has it been identified before? 

Tweak the algorithm for MS2 cosine similarity. Include the reverse dot product.

Clean up any import from public databases to de-replicate compounds we have standards for (we know that a peak isn't leucine because we know when leucine comes out).  

A Shiny/RaMS app will be used to visualize or overview the data. 

Include options for PubMed, HMDB.

Host a small library of "representative" spectra from a bunch of organisms, and from our standards, for quick manual/visual inspection via Shiny, using code developed by WKumler. 

A set of functions for looking at/extracting EICs/MS2s from a small subset of samples (pooled, DDA).

Inclusion list: A list of masses that we tell the MS to get good MS2 data for. This already exists but needs to be incorporated into a systematic update system. Eventually we will generate it from the database (barring the 500 upper limit). 
Right now it’s just compounds we have standards for.
In the future: we could build a list with cmpds we see or suspect we see or ones we have good MS2s for.....some iteration of that.


MSDial-ingestible: Connect ms2 data that we have to the standards list, search that programmatically and export it into an msdial readable database (this is lower priority).


### Other comments

- Fragment matching: % of library sample found in fragments. 
    Example, experimental spectra has *110.97466, 100;* 110.03485, 39.1; *58.02862, 33.5;* 68.01299, 26.6; 111.01888, 20.6.
    Library spectra has               *110.97466, 100;* 109.00000, 40.1; *58.02862, 33.5;* 70.33989, 26.6; 121.04950, 15.0.
    If the above two lines were identical, the fragment match would be 100%. In this situation, the fragment match would be 40% or 0.4.
- The "replacing" of the theoretical values to cut down on columns should be a hidden function.
- For retention time, use the standard runs that are in the same batches to calibrate retention time. This would be BEFORE entering MARS. MARS will not facilitate this step most likely. 

- For DDA high resolution, the mass spec sees a high signal. When it see that, it takes above and below that signal and isolates it in the collision chamber. In the ms2 df, the first column is the exact mass with an intensity of 100 (maximum), then second mass and intensity, etc. 

